server:
  port: 8085
hm:
  swagger:
    title: 支付服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
feign:
  okhttp:
    enabled: true
spring:
  rabbitmq:
    host: 10.41.5.44 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123